/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-04-08 15:56:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.immobilier.model.User;
import com.immobilier.model.Annonce;
import java.util.List;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.immobilier.model.Annonce");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.immobilier.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

User user = (User) session.getAttribute("user");
if(user == null) response.sendRedirect("connexion");
List<Annonce> annonces = (List<Annonce>) request.getAttribute("annonces");
String message = (String) session.getAttribute("message");
if(message != null) {
    session.removeAttribute("message");
}
String erreur = (String) request.getAttribute("erreur");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head><meta charset=\"UTF-8\"><title>Accueil - Immobilier</title><link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"></head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">🏠 Immobilier de Chez Nous</a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"nouvelle-annonce\">📝 Déposer une annonce</a></li>\n");
      out.write("                <li class=\"nav-item\"><span class=\"nav-link\">👤 ");
      out.print( user.getNom() );
      out.write("</span></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"deconnexion\">🚪 Déconnexion</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<div class=\"container mt-4\">\n");
      out.write("    ");
 if(message != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-success alert-dismissible fade show\" role=\"alert\">\n");
      out.write("            ");
      out.print( message );
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if(erreur != null) { 
      out.write("\n");
      out.write("        <div class=\"alert alert-danger alert-dismissible fade show\" role=\"alert\">\n");
      out.write("            ");
      out.print( erreur );
      out.write("\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"></button>\n");
      out.write("        </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("    <h1 class=\"mb-4\">Bienvenue, ");
      out.print( user.getNom() );
      out.write(" !</h1>\n");
      out.write("    <p class=\"lead\">Email: ");
      out.print( user.getEmail() );
      out.write(" | Rôle: ");
      out.print( user.getRole() );
      out.write("</p>\n");
      out.write("    <hr>\n");
      out.write("    \n");
      out.write("    <h2 class=\"mb-3\">📢 Annonces immobilières</h2>\n");
      out.write("    <div class=\"row\">\n");
      out.write("        ");
 if(annonces != null && !annonces.isEmpty()) {
            for(Annonce a : annonces) { 
      out.write("\n");
      out.write("                <div class=\"col-md-4 mb-4\">\n");
      out.write("                    <div class=\"card h-100 shadow-sm\">\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <h5 class=\"card-title text-primary\">");
      out.print( a.getTitre() );
      out.write("</h5>\n");
      out.write("                            <h6 class=\"card-subtitle mb-2 text-muted\">\n");
      out.write("                                📍 ");
      out.print( a.getVille() );
      out.write(' ');
      out.write('-');
      out.write(' ');
      out.print( a.getType() );
      out.write("\n");
      out.write("                            </h6>\n");
      out.write("                            <p class=\"card-text\">");
      out.print( a.getDescription().length() > 100 ? a.getDescription().substring(0,100)+"..." : a.getDescription() );
      out.write("</p>\n");
      out.write("                            <div class=\"mt-2\">\n");
      out.write("                                <span class=\"badge bg-success\">💰 ");
      out.print( String.format("%,.0f", a.getPrix()) );
      out.write(" FCFA</span>\n");
      out.write("                                <span class=\"badge bg-info\">📐 ");
      out.print( a.getSurface() );
      out.write(" m²</span>\n");
      out.write("                                <span class=\"badge bg-secondary\">🛏️ ");
      out.print( a.getPiece() );
      out.write(" pièces</span>\n");
      out.write("                            </div>\n");
      out.write("                            <hr>\n");
      out.write("                            <div class=\"d-flex justify-content-between align-items-center mt-2\">\n");
      out.write("                                <small class=\"text-muted\">\n");
      out.write("                                    👤 Posté par : <strong>");
      out.print( a.getProprietaireNom() );
      out.write("</strong>\n");
      out.write("                                </small>\n");
      out.write("                                ");
 if(user.getId() == a.getUtilisateurId() || "admin".equals(user.getRole())) { 
      out.write("\n");
      out.write("                                    <a href=\"supprimer-annonce?id=");
      out.print( a.getId() );
      out.write("\" class=\"btn btn-sm btn-danger\" onclick=\"return confirm('Supprimer cette annonce ?')\">🗑️ Supprimer</a>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("        ");
  }
        } else { 
      out.write("\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <div class=\"alert alert-info text-center\">\n");
      out.write("                    📭 Aucune annonce pour le moment. \n");
      out.write("                    <a href=\"nouvelle-annonce\" class=\"alert-link\">Soyez le premier à en déposer une !</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
